version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm i
  build:
    commands:
      - npm run build:dev
artifacts:
  files:
    - "**/*"
  type: zip
  base-directory: "dist/vloggerstv"
